version: '3.8'

services:

  mongodb:
    image: mongo
    restart: always
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"    
    environment:
        MONGO_INITDB_ROOT_USERNAME: dil
        MONGO_INITDB_ROOT_PASSWORD: dil
        MONGO_INITDB_DATABASE: admin
    healthcheck:
      test:  echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u dil -p dil --quiet | grep 1
      interval: 20s
      timeout: 10s
      start_period: 330s  
    volumes:
      - ./DIL-project/mongodb/data:/data/db
      - ./DIL-project/mongodb/conf:/data/configdb

    networks:
      - mongo-compose-network
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: test
      ME_CONFIG_BASICAUTH_PASSWORD: test
      ME_CONFIG_MONGODB_ADMINUSERNAME: dil
      ME_CONFIG_MONGODB_ADMINPASSWORD: dil
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_REQUEST_SIZE: 100kb
    networks:
      - mongo-compose-network
    depends_on:
      - mongodb

networks: 
    mongo-compose-network:
      driver: bridge
